(rule
 (with-stdout-to
  dune.corrected
  (run
   ocsigen-dune-rules
   gen-application
   --server-libraries
   ocsipersist-sqlite,ocsigenserver.ext.staticmod
   --eliom-libraries
   my_lib
   my_app
   --dune
   %{dep:dune})))

; [ocsigen-dune-rules] Do not remove this line.
; Below this line, any changes will be overwritten.
;
; To update the rules below, modify the invocation of ocsigen-dune-rules above
; and run:
;
;     dune runtest --auto-promote
;

(rule
 (alias runtest)
 (action
  (diff dune dune.corrected)))

(library
 (public_name my_app)
 (name my_app)
 (modes byte native)
 (library_flags
  (:standard -linkall))
 (preprocess
  (pps
   eliom.ppx.server
   ocsigen-ppx-rpc
   js_of_ocaml-ppx_deriving_json
   --rpc-raw))
 (libraries
  eliom.server
  ocsipersist-sqlite
  ocsigenserver.ext.staticmod
  my_lib.server))

(subdir
 client
 (executable
  (name my_app)
  (modes js byte)
  (preprocess
   (pps js_of_ocaml-ppx js_of_ocaml-ppx_deriving_json))
  (js_of_ocaml
   (build_runtime_flags :standard --enable use-js-string)
   (flags :standard --enable with-js-error --enable use-js-string))
  (libraries eliom.client js_of_ocaml js_of_ocaml-lwt my_lib.client))
 (dynamic_include ../dune.client))

(rule
 (deps
  (glob_files *.eliom)
  (glob_files *.eliomi))
 (action
  (with-stdout-to
   dune.client
   (run ocsigen-dune-rules gen-client-modules .))))

(rule
 (alias runtest)
 (action
  (run
   ocsigen-dune-rules
   check-modules
   --client
   %{dep:client/my_app.bc}
   --server
   %{dep:my_app.cma})))
